### ISSUE TITLE
MSFT Outlook VBO

### ISSUE THREAD

**Issue by jschwarze44** [blue-prism/ms-outlook-utility#4]
•	We imported the recent version of the MS Outlook VBO from the GitHub provided in the DX Platform
•	After importing the VBO in our Blue Prism platform, the formatting of all elements (position within the object) is crashed. All elements are stacked on one position, resulting in hundreds of errors (due to the position of exceptions/blocks)
•	We are using Blue Prism Version 6.3

**Comment by EricWilson-BluePrism** [comment]
Hi @jschwarze44,

This is a known issue. It's due to the VBO being updated (exported) from a newer release of Blue Prism. I believe in v6.6 there was a change to the XML that describes VBOs/processes to where attribute values were moved. There is a tool available on the DX that fixes this. You can find it here: 

https://digitalexchange.blueprism.com/dx/entry/9648/solution/blue-prism-studio-display-fix

Give me about 20 minutes though and I'll update the VBO so that it will work with 6.3 again.

Cheers,
Eric

**Comment by EricWilson-BluePrism** [comment]
@jschwarze44,

The VBO has been updated, using the Studio Display Fix utility, so you should be good to go.

Cheers,
Eric
